 title = "teste_multiclasses"

[owner]
name = "Projeto_PL"

[database]

[database.values]
enabled = [123,0x21c,1923-12-02,[123,'listalista']]
ports = [1234,1234,4321]
data = 1979-05-27T07:32:00-7:00
temp_targets = 23.21e231

[database.ERROR]
error = 'error'